/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package junit.load.test;

import org.junit.jupiter.api.Test;

import java.util.Random;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    @LoadTest(cycles = 5, errorThreshold = 0)
    void randomTest() {
        int random = new Random().nextInt();
        assertEquals(0, random%2);
    }
}
