/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.0.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter API for testing.
    implementation("org.junit.jupiter:junit-jupiter-api:5.7.2")

    // https://mvnrepository.com/artifact/org.junit.platform/junit-platform-launcher
    implementation("org.junit.platform:junit-platform-launcher:1.7.2")

    // Use JUnit Jupiter Engine for testing.
    implementation("org.junit.jupiter:junit-jupiter-engine:5.7.2")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.0-jre")

    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind
    implementation("com.fasterxml.jackson.core:jackson-databind:2.0.1")
}

application {
    // Define the main class for the application.
    mainClass.set("junit.load.test.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
